# Generated by Django 4.2.4 on 2023-10-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_alter_reserva_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Animal',
                'verbose_name_plural': 'Categorias de Animal',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='reserva',
            name='banho_conclusao',
            field=models.BooleanField(default=False, verbose_name='Banho concluído?'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='categoria_animal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reserva.categoriaanimal', verbose_name='Categoria do Animal'),
        ),
    ]
