# Generated by Django 4.2.4 on 2023-10-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_categoriaanimal_remove_reserva_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='categoria_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.categoriaanimal', verbose_name='Categoria do Animal'),
        ),
    ]
