# Generated by Django 4.2.4 on 2023-10-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_alter_reserva_categoria_animal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria do Animal',
                'verbose_name_plural': 'Categorias de Animal',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='reserva',
            name='categoria_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.categoriaanimal', verbose_name='Categoria do Animal'),
        ),
    ]
