# Generated by Django 4.2.4 on 2023-10-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_categoriaanimal_alter_reserva_categoria_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(help_text='dd/mm/aaaa', verbose_name='Data da Reserva'),
        ),
    ]
