# Generated by Django 4.2.4 on 2023-11-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_alter_reserva_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['data', 'turno'], 'verbose_name': 'Reserva de Banho', 'verbose_name_plural': 'Reservas de Banho'},
        ),
    ]
